apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rishop

resources:
  - ingress.yaml 
  - namespace.yaml
  - backend
  - frontend

commonLabels:
  app.kubernetes.io/part-of: rishop
  app.kubernetes.io/managed-by: kustomize