apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: rishop
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: rishop
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
