apiVersion: v1
kind: Service 
metadata: 
  name: analytics-service
  namespace: rishop
  labels: 
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: rishop
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084